package de.smb1display;
import android.content.Context;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.util.*;

final class TrainingDialogs {
 private static int dp(Context c,int n){return Math.round(n*c.getResources().getDisplayMetrics().density);}
 private static String value(JSONObject s,String key,String unit){if(s==null || !s.has(key) || s.isNull(key))return "—";return String.format(I18n.locale(),"%.1f%s",s.optDouble(key),unit.isEmpty()?"":" "+unit);}
 private static String duration(double seconds){if(!Double.isFinite(seconds))return "—";long n=Math.max(0,(long)seconds);return n>=3600?String.format(I18n.locale(),"%d:%02d:%02d",n/3600,n/60%60,n%60):String.format(I18n.locale(),"%d:%02d",n/60,n%60);}
 static AppDialog details(Context c,JSONObject item,List<JSONObject> all,String date){
  boolean imported=item.optBoolean("imported");JSONObject row=item.optJSONObject("row"),s=imported?row:row.optJSONObject("stats");
  AppDialog dialog=new AppDialog(c,I18n.t(R.string.ui_workout_archive_425),I18n.t(R.string.ui_your_workout_426),date,R.drawable.nav_history);
  LinearLayout hero=new LinearLayout(c);hero.setOrientation(LinearLayout.VERTICAL);hero.setPadding(dp(c,18),dp(c,16),dp(c,18),dp(c,16));hero.setBackgroundResource(R.drawable.hero_background);hero.addView(AppDialog.text(c,I18n.t(R.string.ui_workout_duration_427),11,R.color.hero_ink));TextView time=AppDialog.text(c,duration(s.optDouble(imported?"duration_seconds":"seconds",Double.NaN)),40,R.color.hero_ink);time.setTypeface(android.graphics.Typeface.create("sans-serif-medium",android.graphics.Typeface.NORMAL));hero.addView(time);if(!imported)hero.addView(AppDialog.text(c,I18n.t(R.string.ui_active_time_428)+duration(s.optDouble("active",Double.NaN)),13,R.color.hero_ink));dialog.body.addView(hero);
  metricPair(c,dialog,I18n.t(R.string.ui_distance_328),value(s,imported?"distance_km":"km","km"),I18n.t(R.string.ui_energy_429),value(s,imported?"calories_kcal":"kcal","kcal"));
  metricPair(c,dialog,I18n.t(R.string.ui_avg_power_330),value(s,imported?"average_power_watts":"power","W"),I18n.t(R.string.ui_avg_cadence_430),value(s,imported?"average_cadence_rpm":"cadence","rpm"));
  metricPair(c,dialog,I18n.t(R.string.ui_avg_speed_431),value(s,imported?"average_speed_kmh":"speed","km/h"),I18n.t(R.string.ui_avg_resistance_433),value(s,imported?"average_resistance_level":"resistance",""));
  LinearLayout intensity=dialog.group(I18n.t(R.string.ui_intensity_436));int band=TrainingInsights.band(item,all);TextView label=AppDialog.text(c,TrainingInsights.label(band),18,TrainingInsights.color(band));label.setTypeface(null,android.graphics.Typeface.BOLD);intensity.addView(label);double rate=TrainingInsights.intensity(item);if(Double.isFinite(rate))intensity.addView(AppDialog.text(c,String.format(I18n.locale(),I18n.t(R.string.ui_1f_kcal_per_minute_437),rate),14,R.color.ink));intensity.addView(AppDialog.text(c,I18n.t(R.string.ui_relative_to_comparable_workouts_from_the_same_source_cl_438),13,R.color.muted));
  if(!imported){LinearLayout peaks=dialog.group(I18n.t(R.string.ui_more_metrics_439));dialog.row(peaks,I18n.t(R.string.ui_max_power_440),value(s,"maxPower","W"));dialog.row(peaks,I18n.t(R.string.ui_max_cadence_441),value(s,"maxCadence","rpm"));dialog.row(peaks,I18n.t(R.string.ui_max_speed_442),value(s,"maxSpeed","km/h"));dialog.row(peaks,I18n.t(R.string.ui_mechanical_work_443),value(s,"workKj","kJ"));dialog.row(peaks,I18n.t(R.string.ui_revolutions_444),value(s,"revolutions",""));}
  if(imported){LinearLayout extra=dialog.group(I18n.t(R.string.ui_more_metrics_439));dialog.row(extra,I18n.t(R.string.ui_avg_heart_rate_445),s.optDouble("heart_rate_bpm",0)>0?value(s,"heart_rate_bpm","bpm"):I18n.t(R.string.ui_unavailable_448));String[][] fields={{I18n.t(R.string.ui_active_time_449),"active_seconds"},{I18n.t(R.string.ui_pauses_451),"pause_seconds"},{I18n.t(R.string.ui_max_power_440),"max_power_watts"},{I18n.t(R.string.ui_max_cadence_441),"max_cadence_rpm"},{I18n.t(R.string.ui_max_speed_442),"max_speed_kmh"},{I18n.t(R.string.ui_mechanical_work_443),"mechanical_work_kj"},{I18n.t(R.string.ui_revolutions_444),"crank_revolutions"}};String[] units={"","","W","rpm","km/h","kJ",""};for(int i=0;i<fields.length;i++){String key=fields[i][1];if(s.has(key) && !s.isNull(key))dialog.row(extra,fields[i][0],i<2?duration(s.optDouble(key)):value(s,key,units[i]));}}
  LinearLayout recording=dialog.group(I18n.t(R.string.ui_recording_144));recording.addView(AppDialog.text(c,imported?I18n.t(R.string.ui_imported_from_mybodytone_458):row.optBoolean("rawSaved")?I18n.t(R.string.ui_recording_saved_on_your_phone_459):I18n.t(R.string.ui_recorded_by_your_bridge_460),15,R.color.ink));
  if(imported){recording.addView(AppDialog.text(c,I18n.t(R.string.ui_time_shown_as_reported_by_the_source_per_second_data_is_461),13,R.color.muted));String flags=row.optString("quality_flags");if(flags.contains("heart_rate_zero"))recording.addView(AppDialog.text(c,I18n.t(R.string.ui_a_heart_rate_of_0_probably_indicates_a_missing_reading_464),13,R.color.muted));if(flags.contains("average_power_zero"))recording.addView(AppDialog.text(c,I18n.t(R.string.ui_a_power_value_of_0_was_imported_unchanged_and_is_unveri_466),13,R.color.muted));JSONObject original=row.optJSONObject("original_display");if(original!=null){Button toggle=new Button(c);toggle.setText(I18n.t(R.string.ui_show_original_values_468));toggle.setAllCaps(false);toggle.setTextColor(c.getColor(R.color.accent));toggle.setBackground(AppDialog.interactive(c,R.color.surface_alt,14,false));recording.addView(toggle);LinearLayout originals=new LinearLayout(c);originals.setOrientation(LinearLayout.VERTICAL);originals.setVisibility(View.GONE);recording.addView(originals);Iterator<String> keys=original.keys();while(keys.hasNext()){String key=keys.next();dialog.row(originals,key.equals("Personalwesen")?I18n.t(R.string.ui_heart_rate_source_470):I18n.originalLabel(c,key),original.optString(key));}toggle.setOnClickListener(v->{boolean hidden=originals.getVisibility()!=View.VISIBLE;originals.setVisibility(hidden?View.VISIBLE:View.GONE);toggle.setText(hidden?I18n.t(R.string.ui_hide_original_values_471):I18n.t(R.string.ui_show_original_values_468));});}}
  else recording.addView(AppDialog.text(c,s.optBoolean("estimated")?I18n.t(R.string.ui_calories_estimated_from_power_472):I18n.t(R.string.ui_calories_from_the_bike_energy_counter_473),13,R.color.muted));
  return dialog;
 }
 private static void metricPair(Context c,AppDialog d,String a,String av,String b,String bv){LinearLayout row=new LinearLayout(c);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(c,10);d.body.addView(row,lp);metric(c,row,a,av,false);metric(c,row,b,bv,true);}
 private static void metric(Context c,LinearLayout row,String label,String value,boolean right){LinearLayout tile=new LinearLayout(c);tile.setOrientation(LinearLayout.VERTICAL);tile.setPadding(dp(c,14),dp(c,14),dp(c,14),dp(c,14));tile.setBackground(AppDialog.surface(c,R.color.surface_alt,18,false));tile.addView(AppDialog.text(c,label,12,R.color.muted));TextView number=AppDialog.text(c,value,23,R.color.ink);number.setTypeface(android.graphics.Typeface.create("sans-serif-medium",android.graphics.Typeface.NORMAL));tile.addView(number);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);if(right)lp.leftMargin=dp(c,10);row.addView(tile,lp);}
 static AppDialog comparison(Context c,JSONObject reference,List<JSONObject> all){
  AppDialog d=new AppDialog(c,I18n.t(R.string.ui_workout_comparison_474),I18n.t(R.string.ui_similar_workouts_475),I18n.t(R.string.ui_compare_workouts_with_similar_duration_and_resistance_476),R.drawable.nav_history);
  String text=TrainingInsights.comparison(reference,all);
  for(String block:text.split("\\n\\n")){
   if(block.trim().isEmpty())continue;
   String heading=block.startsWith(I18n.t(R.string.ui_resistance_478))?I18n.t(R.string.ui_comparison_criteria_479):block.startsWith(I18n.t(R.string.ui_avg_cadence_430))?I18n.t(R.string.ui_cadence_comparison_480):block.startsWith(I18n.t(R.string.ui_for_a_trend_481))?I18n.t(R.string.ui_no_trend_yet_482):block.startsWith(I18n.t(R.string.ui_matching_workouts_483))?I18n.t(R.string.ui_matching_workouts_483):I18n.t(R.string.ui_interpretation_484);
   LinearLayout group=d.group(heading);
   if(block.startsWith(I18n.t(R.string.ui_matching_workouts_483))){
    String[] lines=block.split("\\n");for(int i=1;i<lines.length;i++){String[] parts=lines[i].split(" · ",2);TextView date=AppDialog.text(c,parts[0],15,R.color.ink);date.setTypeface(null,android.graphics.Typeface.BOLD);date.setPadding(0,dp(c,8),0,0);group.addView(date);if(parts.length>1)group.addView(AppDialog.text(c,parts[1],13,R.color.muted));}
   }else group.addView(AppDialog.text(c,block.trim(),15,R.color.ink));
  }
  return d;
 }
}
