[platformio]
default_envs = esp32_d1_mini

[env:esp32_d1_mini]
platform = espressif32@6.10.0
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@1.4.3
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=4

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@1.4.3
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=4

[env:history_test]
extends = env:esp32_d1_mini
lib_deps =
lib_extra_dirs = .pio/libdeps/esp32_d1_mini
build_flags =
    ${env:esp32_d1_mini.build_flags}
    -DHISTORY_SELF_TEST

[env:ftms_test]
extends = env:esp32_d1_mini
lib_deps =
lib_extra_dirs = .pio/libdeps/esp32_d1_mini
build_flags =
    ${env:esp32_d1_mini.build_flags}
    -DFTMS_PARSER_SELF_TEST

[env:session_test]
extends = env:esp32_d1_mini
lib_deps =
lib_extra_dirs = .pio/libdeps/esp32_d1_mini
build_flags =
    ${env:esp32_d1_mini.build_flags}
    -DSESSION_SELF_TEST
